line-length = 79
extend-exclude = ["*/_generated/*_pb2*"]
target-version = "py312"

[format]
docstring-code-format = true
docstring-code-line-length = 80

[lint]
preview = false
select = ["ALL"]
ignore = [
  "ANN101", # deprecated
  "ANN102", # deprecated
  "ANN401", # dynamically typed expressions (typing.Any) are disallowed
  "D10", # missing docstrings
  "N818", # Error suffix on exceptions
  "PD", # pandas
  "PLR0913", # too many arguments
  "S311", # pseudo-random number generation
  "TD", # TODO rules
  "ISC001", # implicit string concatenation
  "CPY001", # missing copyright notice
  "PLC0415", # import at top of file
  "COM812", # missing comma
]

[lint.per-file-ignores]
"**/examples/**/*" = [
  "INP001", # implicit namespace packages
  "T", # print
]
"**/scripts/*" = [
  "INP001", # implicit namespace packages
  "T", # print
]
"**/tests/**/*" = [
  "PLC1901", # compare to empty string
  "PLR2004", # magic value comparison
  "PLR6301", # no self use in methods
  "S101", # asserts
  "TID252", # relative imports
]

[lint.isort]
known-first-party = ["flowcean"]

[lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false

[lint.pydocstyle]
convention = "google"
