[default]
extend-ignore-words-re = [
  "MAPE", # MeanAveragePercentageError
  "TPE",  # TreeParzenEstimator
]
extend-ignore-identifiers-re = [
  "OTUtils", # LearnLib convenience wrapper
  "NDArray", # NumPy type alias
  "arange",  # NumPy function
]

[files]
extend-exclude = [
  "java/AutomataLearner/src/main/java/io/flowcean/learner/grpc/*.java",
  "examples/robot_localization_failure/recordings/wgtl_data_collection_experiment_overview.csv",
]
