rosbag:
  training_paths:
    # - recordings/wgtl_half_split/rec_20250821_104113_id_01
    # - recordings/wgtl_half_split/rec_20250821_132354_id_01
    # - recordings/wgtl_half_split/rec_20250821_132354_id_02
    # - recordings/wgtl_half_split/rec_20250821_141846_id_01
    # - recordings/wgtl_half_split/rec_20250821_141846_id_02
    # - recordings/wgtl_half_split/rec_20250821_151429_id_01   #evaluation_cache
    # - recordings/wgtl_half_split/rec_20250822_123916_id_01   #evaluation_cache
    # - recordings/wgtl_half_split/rec_20250822_123916_id_02
    # - recordings/wgtl_half_split/rec_20250822_132819_id_01
    # - recordings/wgtl_half_split/rec_20250822_132819_id_02
    - recordings/wgtl_half_split/rec_20250822_135308_id_01
    - recordings/wgtl_half_split/rec_20250822_135308_id_02
    # - recordings/wgtl_half_split/rec_20250825_100748_id_01
    # - recordings/wgtl_half_split/rec_20250825_100748_id_02
    # - recordings/wgtl_half_split/rec_20250825_133605_id_01
    # - recordings/wgtl_half_split/rec_20250825_133605_id_02
    # - recordings/wgtl_half_split/rec_20250825_135829_id_01
    # - recordings/wgtl_half_split/rec_20250825_135829_id_02
    # - recordings/wgtl_half_split/rec_20250825_145941_id_01
    # - recordings/wgtl_half_split/rec_20250825_145941_id_02
    # - recordings/wgtl_half_split/rec_20250825_153216_id_01
    # - recordings/wgtl_half_split/rec_20250825_153216_id_02
    # - recordings/wgtl_half_split/rec_20250825_161940_id_01
    # - recordings/wgtl_half_split/rec_20250825_161940_id_02
    # - recordings/wgtl_half_split/rec_20250826_095810_id_01
    # - recordings/wgtl_half_split/rec_20250826_102611_id_01
    # - recordings/wgtl_half_split/rec_20250826_102611_id_02
    # - recordings/wgtl_half_split/rec_20250826_104543_id_01
    # - recordings/wgtl_half_split/rec_20250826_104543_id_02
    # - recordings/wgtl_half_split/rec_20250827_161251_id_01
    # - recordings/wgtl_half_split/rec_20250827_161251_id_02
    # - recordings/wgtl_half_split/rec_20250828_102407_id_01
    # - recordings/wgtl_half_split/rec_20250828_102407_id_02
    # - recordings/wgtl_half_split/rec_20250828_105714_id_01
    # - recordings/wgtl_half_split/rec_20250828_105714_id_02
    # - recordings/wgtl_half_split/rec_20250828_161448_id_01
    # - recordings/wgtl_half_split/rec_20250829_104641_id_01
    # - recordings/wgtl_half_split/rec_20250829_104641_id_02

  evaluation_paths:
    # - recordings/wgtl_half_split/rec_20250821_104113_id_02
    # - recordings/wgtl_half_split/rec_20250821_151429_id_02
    # - recordings/wgtl_half_split/rec_20250826_095810_id_02
    - recordings/wgtl_half_split/rec_20250828_161448_id_02

  message_paths:
    - ros_msgs/sensor_msgs/msg/LaserScan.msg
    - ros_msgs/nav2_msgs/msg/Particle.msg
    - ros_msgs/nav2_msgs/msg/ParticleCloud.msg
localization:
  position_threshold: 0.4
  heading_threshold: 0.4
architecture:
  image_size: 256
  width_meters: 15.0
learning:
  batch_size: 64
  learning_rate: 0.0001
  epochs: 10 #50
  preload: true
  disk_cache_dir: "learning_cache"
  eval_cache_dir: "evaluation_cache"          # evaluation cache directory
  clear_eval_cache: false                     # whether to clear the evaluation cache before use
  model_path: "models/robot_localization.fml"
optuna:
  storage: "sqlite:///optuna.db"
  trials: 10 # 30
  hyperparameters:
    learning_rate:
      low: 1e-5
      high: 1e-2
    batch_size:
      choices: [32, 64, 128]
    image_size:
      choices: [256, 512, 768]
    width_meters:
      low: 5.0
      high: 50.0
