rosbag:
  training_paths:
    - recordings/rec_20250923_135805_id_01
  evaluation_paths:
    - recordings/rec_20250923_135805_id_01 
  message_paths:
    - ros_msgs/sensor_msgs/msg/LaserScan.msg
    - ros_msgs/nav2_msgs/msg/Particle.msg
    - ros_msgs/nav2_msgs/msg/ParticleCloud.msg
localization:
  position_threshold: 0.4
  heading_threshold: 0.4
architecture:
  image_size: 150
  width_meters: 15.0
learning:
  batch_size: 128
  learning_rate: 0.0001
  epochs: 2
  model_path: "models/robot_localization.model"
optuna:
  storage: "sqlite:///optuna.db"
