rosbag:
  training_paths:
    # - recordings/wgtl_half_split/rec_20250825_161940_id_01 # map: unsymmetric_exp_2, static & dynamic obstacles
    # - recordings/wgtl_half_split/rec_20250825_161940_id_02 # map: unsymmetric_exp_2, static & dynamic obstacles
    # - recordings/wgtl_half_split/rec_20250822_135308_id_02 # map: symmetric_exp_2, dynamic obstacles
    # - recordings/wgtl_half_split/rec_20250825_153216_id_02 # map: unsymmetric_exp_2, only static obstacles  
    # - recordings/wgtl_half_split/rec_20250822_135308_id_01 # map: symmetric_exp_2, dynamic obstacles
    # - recordings/wgtl_half_split/rec_20250825_153216_id_01 # map: unsymmetric_exp_2, only static obstacles
    # - recordings/momo_real_world_data/rosbag2_2025_11_12-16_38_21
    - recordings/test_data/test_1/training_data_half/rec_20250923_135805_id_01
    - recordings/test_data/test_1/training_data_half/rec_20250923_135805_id_02
    # - recordings/test_data/test_2/data_half/rec_20250923_145058_id_01
    # - recordings/test_data/test_2/data_half/rec_20250923_145058_id_02


  evaluation_paths:
    # - recordings/real_world_data
    # - recordings/momo_real_world_data/rosbag2_2025_11_13-14_53_15
    - recordings/test_data/test_1/testing_data_half/rec_20250923_142005_id_01
    - recordings/test_data/test_1/testing_data_half/rec_20250923_142005_id_02
    # - recordings/test_data/test_2/data_half/rec_20250923_153128_id_01
    # - recordings/test_data/test_2/data_half/rec_20250923_153128_id_02


  message_paths:
    - ros_msgs/sensor_msgs/msg/LaserScan.msg
    - ros_msgs/nav2_msgs/msg/Particle.msg
    - ros_msgs/nav2_msgs/msg/ParticleCloud.msg
localization:
  position_threshold: 0.4
  heading_threshold: 0.4
architecture:
  image_size: 100 #640
  width_meters: 20.0 
learning:
  batch_size: 16
  learning_rate: 0.0001
  epochs: 50
  preload: true
  disk_cache_dir: "learning_cache"
  model_path: "models/train_on_sim_test_on_real_data.fml"

optuna:
  storage: "sqlite:///optuna.db"
  trials: 100
  hyperparameters:
    learning_rate:
      low: 1e-5
      high: 1e-2
    batch_size:
      choices: [16, 32]
    image_size:
      choices: [100,120,140,160]
    width_meters:
      low: 2.0
      high: 30.0