rosbag:
  training_paths:
    - toy_data/training_data_half/rec_20250923_135805_id_01
    # - toy_data/training_data_half/rec_20250923_135805_id_02
  evaluation_paths:
    - toy_data/testing_data_half/rec_20250923_142005_id_01
    # - toy_data/testing_data_half/rec_20250923_142005_id_02
  message_paths:
    - ros_msgs/sensor_msgs/msg/LaserScan.msg
    - ros_msgs/nav2_msgs/msg/Particle.msg
    - ros_msgs/nav2_msgs/msg/ParticleCloud.msg
localization:
  position_threshold: 0.4
  heading_threshold: 0.4
architecture:
  image_size: 150
  width_meters: 15.0
learning:
  batch_size: 128
  learning_rate: 0.0001
  epochs: 2
  model_path: "models/robot_localization.model"
optuna:
  storage: "sqlite:///optuna.db"
