[project]
name = "hybrid-systems"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "flowcean",
    "matplotlib>=3.10.6",
]

[tool.pyright]
extends = "../../pyproject.toml"

[tool.uv.sources]
flowcean = { workspace = true }
