name: Check
on: [pull_request]
jobs:
  format-and-lint:
    name: Check Formatting and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            .github/workflows/pull_request.yml
      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          hatch --version
      - name: Check Formatting
        run: |
          hatch fmt --check
      - name: Create Environment
        run: |
          hatch --verbose env create types
      - name: Check types
        run: |
          hatch --verbose run types:check

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            .github/workflows/pull_request.yml
      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          hatch --version
      - name: Create Environment
        run: |
          hatch --verbose env create tests
      - name: Run Tests
        run: |
          hatch --verbose run tests:report-xml

  examples:
    name: Run Examples
    strategy:
      matrix:
        example: ["boiler", "failure_time_prediction", "linear_data"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            .github/workflows/pull_request.yml
      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          hatch --version
      - name: Install and Setup DVC
        run: |
          pip install dvc dvc-webdav
          dvc --version
          dvc remote modify --local tuhh-cloud password ${{ secrets.TUHH_CLOUD_DVC_SHARE_PASSWORD }}
      - name: DVC pull
        run: |
          dvc pull --recursive examples/${{ matrix.example }}
      - name: Create Environment
        run: |
          hatch --verbose env create examples
      - name: Run Example
        run: |
          hatch --verbose run examples:${{ matrix.example }}

  documentation:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            .github/workflows/pull_request.yml
      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          hatch --version
      - name: Create Environment
        run: |
          hatch --verbose env create docs
      - name: Build Documentation
        run: |
          hatch --verbose run docs:build
